apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalog-mongodb
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: catalog-mongodb
    spec:
      volumes:
      - name: data
        emptyDir: {}
      containers:
      - name: mongo
        image: mongo:3.4.10
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: data
          mountPath: /data/db/
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-mongodb
  namespace: default
spec:
  selector:
    app: catalog-mongodb
  ports:
  - port: 27017
